"""
Tower A - Prototype 1 - tests/parity_check.py

Purpose
Validates that the live Tower A backend produces scores numerically identical to those generated by the offline Python
training pipeline.

This is the parity validation script. It confirms that:
  - The model loaded by the backend is the same as the evaluated model.
  - The feature extraction pipeline is byte-for-byte identical between training (data_processing/) and deployment (backend/).
  - No numeric drift has been introduced by serialisation (joblib) or by the FastAPI request/response layer.

"""

from __future__ import annotations

import sys
import json
from pathlib import Path

import numpy as np
import requests

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

# 20 test URLs covering a range of risk levels
TEST_URLS = [
    # Benign - major domains
    "https://www.google.com/",
    "https://www.bbc.co.uk/news",
    "https://github.com/Dakshit2203/ML-Detection-Extension",
    "https://www.amazon.co.uk/",
    "https://stackoverflow.com/questions/tagged/python",
    # Benign - longer paths
    "https://en.wikipedia.org/wiki/Phishing",
    "https://www.gov.uk/government/publications",
    "https://mail.google.com/mail/u/0/#inbox",
    # Borderline / interesting lexical patterns
    "https://paypal-update.secure-verify.com/login",
    "https://accounts.google.com-secure-login.xyz/signin",
    "http://192.168.1.1/admin",
    "https://bit.ly/3AbcXYZ",
    "https://example.com/verify-your-account?token=abc123",
    "http://login.microsoftonline.com.phishing.cc/auth",
    # Low-complexity benign
    "https://reddit.com/r/learnpython/comments/abc",
    "https://news.ycombinator.com/",
    "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    # Typical phishing pattern URLs
    "http://secure-paypal.com/webscr?cmd=_login-run",
    "http://update-your-bank-details.info/NatWest/login",
    "https://apple-id-verify-now.com/appleid/auth",
]

API_URL = "http://127.0.0.1:8000"

# Offline scoring (direct Python inference, no HTTP)
def offline_score(url: str) -> float:
    """
    Computes p_phish directly via the Python inference pipeline, bypassing the FastAPI layer entirely.

    This uses the same TowerAInference class that the backend uses, applied directly without HTTP serialisation.
    """
    from backend.config import MODEL_PATH, FEATURE_SPEC_PATH, FEATURES_DIR
    from backend.inference import TowerAInference
    from backend.url_normalise import normalise_url_for_inference

    # Instantiate fresh (avoids state pollution from the backend's singleton)
    predictor = TowerAInference(MODEL_PATH, FEATURE_SPEC_PATH, FEATURES_DIR)
    url_norm  = normalise_url_for_inference(url)
    return predictor.predict_proba(url_norm)

# Online scoring (via live backend)
def online_score(url: str) -> float:
    """
    Sends the URL to the live backend /predict endpoint and returns p_phish.
    Raises an exception if the backend is not reachable.
    """
    response = requests.post(
        f"{API_URL}/predict",
        json={"url": url, "mode": "parity_check"},
        timeout=10
    )
    response.raise_for_status()
    data = response.json()

    if data.get("skipped"):
        raise ValueError(f"URL was skipped by backend: {url}")
    if data.get("p_phish") is None:
        raise ValueError(f"Backend returned no p_phish for: {url}")

    return float(data["p_phish"])

# Main parity check
def main() -> None:
    print("=" * 70)
    print("Tower A - Parity Check")
    print(f"Backend: {API_URL}")
    print(f"Test URLs: {len(TEST_URLS)}")
    print("=" * 70)

    # Check backend is reachable
    try:
        health = requests.get(f"{API_URL}/health", timeout=5).json()
        print(f"Backend health: {health.get('status', 'unknown')}")
        print(f"Buffer size: {health.get('buffer_size', '?')}")
    except requests.exceptions.ConnectionError:
        print(f"\nERROR: Cannot reach backend at {API_URL}")
        print("Start the backend first:")
        print(" uvicorn backend.app:app --host 127.0.0.1 --port 8000")
        sys.exit(1)

    print()

    diffs = []
    pass_count = 0
    fail_count = 0

    for url in TEST_URLS:
        try:
            p_offline = offline_score(url)
            p_online = online_score(url)
            diff = abs(p_offline - p_online)
            diffs.append(diff)

            status = "✓" if diff < 1e-5 else "✗"
            if diff < 1e-5:
                pass_count += 1
            else:
                fail_count += 1

            print(f"{status} |Diff|={diff:.2e} offline={p_offline:.6f} online={p_online:.6f}")
            print(f" {url[:80]}")

        except Exception as e:
            fail_count += 1
            print(f"✗ ERROR: {e}")
            print(f" {url[:80]}")

    print()
    print("=" * 70)

    if diffs:
        max_diff = max(diffs)
        print(f"Max |Diff|: {max_diff:.2e}")
        print(f"Mean |Diff|: {np.mean(diffs):.2e}")
        print(f"URLs passed: {pass_count}/{len(TEST_URLS)}")
        print()

        if max_diff < 1e-5 and fail_count == 0:
            print("RESULT: PASS - backend scores are numerically identical to offline pipeline.")
            print("        This confirms parity between the evaluated model and the deployed model.")
        else:
            print("RESULT: FAIL - unexpected numeric difference detected.")
            print("        Check that model_lr.joblib and feature_spec.json are from Phase 5.")
    else:
        print("RESULT: No successful comparisons - check backend connectivity.")

    print("=" * 70)


if __name__ == "__main__":
    main()